logging:
  level:
    liquibase: INFO
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE

spring:
  datasource:
    password: root
    url: 'jdbc:postgresql://localhost:5432/postgres'
    username: postgres
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  liquibase:
    change-log: 'classpath:/db/changelog-master.xml'
  thymeleaf:
    cache: false


server:
  servlet:
    session:
      timeout: 120000m
